{% set name = "txl-remote-contents" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_remote_contents-{{ version }}.tar.gz
  sha256: 9810d985e65e327351194443d01fa830be72039a121fd8c79cc073ded114dab7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl >=0.2.18,<0.3.0
    - httpx >=0.23.1
    - httpx-ws >=0.4.2
    - pycrdt >=0.8.11,<0.9.0
    - pycrdt-websocket >=0.13.0,<0.14.0
    - jupyter_ydoc >=2.0.0,<3.0.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_remote_contents

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_contents
  summary: TXL plugin for remote contents
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_contents
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
