{% set python_min = "3.10" %}
{% set name = "txl-remote-contents" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_remote_contents-{{ version }}.tar.gz
  sha256: 3f7d331b138991abbcb6632a9e964a40b9de3db8215975b242bcf8a5c272e75b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0
    - httpx >=0.23.1
    - httpx-ws >=0.4.2
    - pycrdt >=0.10.9,<0.11.0
    - pycrdt-websocket >=0.15.3,<0.16.0
    - jupyter_ydoc >=3.0.2,<4.0.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_remote_contents

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_contents
  summary: TXL plugin for remote contents
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_contents
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
